// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }





// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800"],
//   variable: "--font-poppins",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "CuroAid",
//   description: "CuroAid",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className= {poppins.className}>
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { BookingProvider } from "./components/booking/bookingprovider";
import { imgDoctorAtHome } from "@/lib/assets";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "CuroAid | Home Healthcare Services",
    template: "%s | CuroAid",
  },
  description:
    "CuroAid provides professional home healthcare services including Doctor at Home, home nursing, physiotherapy, elder care, wound care and more.",
  metadataBase: new URL("https://curoaid.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "CuroAid | Home Healthcare Services",
    description:
      "Professional, personalized and compassionate healthcare services delivered to your doorstep.",
    url: "https://curoaid.com",
    siteName: "CuroAid",
    type: "website",
    images: [
      {
        url: imgDoctorAtHome,
        width: 1200,
        height: 630,
        alt: "CuroAid Doctor at Home Services",
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <BookingProvider>

          {children}
        </BookingProvider>
      </body>
    </html>
  );
}